"""Refresh CategoryNew tree from PKULaw live API.

Fetches the full 4-level category tree and regenerates src/config_data.py.

Usage: python scripts/refresh_categories.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONFIG_DATA_PATH = PROJECT_ROOT / "src" / "config_data.py"

CLUSTER_API_URL = "/searchingapi/adv/cluster/pfnl"

CRIME_NAMES = [
    "危险驾驶罪",
    "交通肇事罪",
    "盗窃罪",
    "诈骗罪",
    "合同诈骗罪",
    "故意伤害罪",
    "强奸罪",
    "非法拘禁罪",
    "抢劫罪",
    "抢夺罪",
    "敲诈勒索罪",
    "妨害公务罪",
    "聚众斗殴罪",
    "寻衅滋事罪",
    "掩饰、隐瞒犯罪所得、犯罪所得收益罪",
    "走私、贩卖、运输、制造毒品罪",
    "非法持有毒品罪",
    "容留他人吸毒罪",
    "信用卡诈骗罪",
    "故意毁坏财物罪",
]


def flatten_tree(items: list[dict]) -> dict[str, str]:
    """Recursively flatten CategoryNew tree into name-ID pairs."""
    result = {}
    for item in items:
        result.setdefault(item["name"], item.get("id", ""))
        children = item.get("children") or []
        if children:
            for k, v in flatten_tree(children).items():
                result.setdefault(k, v)
    return result


def build_category_tree(items: list[dict]) -> dict:
    """Recursively build hierarchical tree dict."""
    result = {}
    for item in items:
        name = item["name"]
        vid = item.get("id", "")
        children = item.get("children") or []
        if children:
            result[name] = {"id": vid, "children": build_category_tree(children)}
        else:
            result[name] = vid
    return result


def fetch_category_tree(page, token: str) -> list[dict]:
    """Fetch full CategoryNew tree from PKULaw API."""
    data = page.evaluate(
        """async ([url, token]) => {
            const resp = await fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': token,
                },
                body: JSON.stringify({"dimensionId": "CategoryNew"})
            });
            return await resp.json();
        }""",
        [CLUSTER_API_URL, token],
    )
    if isinstance(data, list) and data:
        dim = next((d for d in data if d.get("id") == "CategoryNew"), None)
        if dim:
            return dim.get("list") or []
    raise RuntimeError(f"Failed to fetch CategoryNew tree: {data}")


def _format_tree(d: dict, indent: int = 0) -> str:
    """Format a nested dict as Python source for CATEGORY_TREE."""
    prefix = "    " * indent
    if not d:
        return "{}"
    parts = []
    for key, value in d.items():
        if isinstance(value, dict):
            if "id" in value and "children" in value:
                inner = _format_tree(value["children"], indent + 2)
                parts.append(
                    f'{prefix}    "{key}": {{"id": "{value["id"]}", '
                    f'"children": {inner}}},'
                )
            else:
                inner = _format_tree(value, indent + 1)
                parts.append(f'{prefix}    "{key}": {inner},')
        else:
            parts.append(f'{prefix}    "{key}": "{value}",')
    return "{\n" + "\n".join(parts) + f"\n{prefix}}}"


def generate_config_data(new_values: dict[str, str], new_tree: dict) -> None:
    """Regenerate src/config_data.py with updated CategoryNew data."""
    from src.config_data import CLUSTER_DIMENSIONS, FIELD_DEFINITIONS

    updated_dims = {}
    for dim_id, dim_data in CLUSTER_DIMENSIONS.items():
        if dim_id == "CategoryNew":
            updated_dims[dim_id] = {"title": "案由", "values": new_values}
        else:
            updated_dims[dim_id] = dim_data

    lines = [
        '"""Auto-generated PKULaw API field mappings.',
        "",
        "Regenerated by: python scripts/refresh_categories.py",
        '"""',
        "",
    ]

    lines.append("FIELD_DEFINITIONS = {")
    for field_name, field_data in FIELD_DEFINITIONS.items():
        lines.append(f'    "{field_name}": {{')
        lines.append(f'        "show_text": "{field_data["show_text"]}",')
        lines.append(f'        "type": "{field_data["type"]}",')
        lines.append(f'        "order": {field_data["order"]},')
        lines.append("    },")
    lines.append("}")
    lines.append("")

    lines.append("CLUSTER_DIMENSIONS = {")
    for dim_id, dim_data in updated_dims.items():
        lines.append(f'    "{dim_id}": {{')
        lines.append(f'        "title": "{dim_data["title"]}",')
        lines.append(
            f'        "values": {json.dumps(dim_data["values"], ensure_ascii=False)},'
        )
        lines.append("    },")
    lines.append("}")
    lines.append("")

    tree_str = _format_tree(new_tree, indent=0)
    lines.append("CATEGORY_TREE = " + tree_str)
    lines.append("")

    CONFIG_DATA_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Updated {CONFIG_DATA_PATH} ({CONFIG_DATA_PATH.stat().st_size} bytes)")


def main():
    from src.auth import authenticate, close_browser, launch_browser

    print("Launching browser...")
    pw, browser, context, page = launch_browser()
    try:
        print("Authenticating...")
        token = authenticate(page)

        print("Fetching CategoryNew tree...")
        tree_data = fetch_category_tree(page, token)
        print(f"Got {len(tree_data)} top-level entries")

        values = flatten_tree(tree_data)
        print(f"Flattened to {len(values)} name-ID pairs")

        tree = build_category_tree(tree_data)
        print(f"Built tree with {len(tree)} top-level keys")

        missing = [n for n in CRIME_NAMES if n not in values]
        if missing:
            print(f"WARNING: {len(missing)} crime names still missing: {missing}")
        else:
            print("All 20 crime names resolved!")

        generate_config_data(values, tree)
        print("Done!")
    finally:
        close_browser(pw, browser)


if __name__ == "__main__":
    main()
